### ISSUE TITLE
[Feature] wezterm light theme?

### ISSUE THREAD

**Issue by vihu** [Tsuzat/NeoSolarized.nvim#10]
Can you please add support for wezterm light theme?

**Comment by Tsuzat** [comment]
Hello @vihu,

Your work on the wezterm dark theme is highly appreciated. I, myself, do not use wezterm but kitty. Regarding your request for adding a light theme, it would be great if you could provide some guidance on how themes work for wezterm, or if you could contribute the code yourself, that would be fantastic. I appreciate your help and look forward to your continued contributions.

Happy Coding. ❤

**Comment by vihu** [comment]
> Hello @vihu,
> 
> Your work on the wezterm dark theme is highly appreciated. I, myself, do not use wezterm but kitty. Regarding your request for adding a light theme, it would be great if you could provide some guidance on how themes work for wezterm, or if you could contribute the code yourself, that would be fantastic. I appreciate your help and look forward to your continued contributions.
> 
> Happy Coding. heart

If you can provide me a kitty Neosolarized-light theme, I can easily port it to wezterm and open a PR. I am, however, not an expert on picking the right colors :sweat_smile: so I cannot write a light terminal theme from scratch.

**Comment by Tsuzat** [comment]
hey @vihu , I have added a light theme for the kitty terminal in this [commit](https://github.com/Tsuzat/NeoSolarized.nvim/commit/7cec110ca17219a2a2b7550782ecdb8a3e364447). Take a look. Feedbacks are welcomed.
