### ISSUE TITLE
switching style dynamically

### ISSUE THREAD

**Issue by eprst** [Tsuzat/NeoSolarized.nvim#15]
Hi
Is there any way to dynamically change the style (dark/light)? `:set background=dark/light` doesn't work.
Thanks

**Comment by Tsuzat** [comment]
Hi @eprst , You can change the theme using `:set background=light` 

https://github.com/Tsuzat/NeoSolarized.nvim/assets/70003855/bbb48627-3d0a-4110-9660-753828c6ecd7

I'll suggest to have transparency disabled. otherwise you'll feel that it's not woking, although, it still is working. 
```lua
required("NeoSolarized").setup {
  transparent = false,
}
```

**Comment by eprst** [comment]
Yes, `transparent=false` was the key. Thank you!
