### ISSUE TITLE
Modify WinSeparator color

### ISSUE THREAD

**Issue by 9enki** [Tsuzat/NeoSolarized.nvim#16]
I would like to make the `WinSeparator` color a little lighter than `c.bg0` . Is there any other way than rewriting this value directly in my local?

https://github.com/Tsuzat/NeoSolarized.nvim/blob/c28b7f9bdc48a9017480da41529ef63ab6ccb885/lua/NeoSolarized/theme.lua#L79

**Comment by 9enki** [comment]
Sorry for creating a new issue even though it was discussed in a past issue.

https://github.com/Tsuzat/NeoSolarized.nvim/issues/5

I was able to achieve what I wanted to do with the following settings. Thank you.

```lua
require("NeoSolarized").setup({
  on_highlights = function(highlights, colors)
    highlights.WinSeparator.fg = "#abcdef"
  end,
})
vim.cmd([[colorscheme NeoSolarized]])

```

**Comment by Tsuzat** [comment]
Not a problem. Happy Coding ❤️
