### ISSUE TITLE
Theme color suggestions and discussion

### ISSUE THREAD

**Issue by komputerwiz** [Tsuzat/NeoSolarized.nvim#19]
Thanks for the great work on the theme! I switched over from another solarized theme that didn't support tree-sitter, and now my editor feels so vibrant! :slightly_smiling_face:

I noticed a few things that might need some discussion, and I'm happy to submit a pull request for whatever gets decided here.

# DiffChange

When in diff mode, additions and deletions are highlighted, but changes are challenging to find:

![Screenshot from 2024-02-22 18-35-01](https://github.com/Tsuzat/NeoSolarized.nvim/assets/369238/e2e68819-6b6f-4138-8cee-174ef85e28cb)

I noticed [theme.lua](https://github.com/Tsuzat/NeoSolarized.nvim/blob/3089cb703e947e6433a2c2c1191b97e63804b300/lua/NeoSolarized/theme.lua#L25) references `c.diff_yellow`, but [colors.lua](https://github.com/Tsuzat/NeoSolarized.nvim/blob/3089cb703e947e6433a2c2c1191b97e63804b300/lua/NeoSolarized/colors.lua#L26) defines `diff_change`. Probably just a typo. Changing `DiffChange.bg` to `c.diff_change` produces the following:

![Screenshot from 2024-02-22 18-42-48](https://github.com/Tsuzat/NeoSolarized.nvim/assets/369238/4a7ecac1-d2f1-4250-a834-3baffc5ebf91)

Changed lines are easier to spot, but I wonder if `bg1` is right for the `DiffText`. May I suggest a slightly more intense version of the `DiffChange` color? (The screenshot uses `#404000`)

![Screenshot from 2024-02-22 18-47-54](https://github.com/Tsuzat/NeoSolarized.nvim/assets/369238/d9bdff74-6bf5-4c9d-aae6-5b260f072af6)

Regardless, I think the colors should be adjusted to work in light mode:

![Screenshot from 2024-02-22 18-49-27](https://github.com/Tsuzat/NeoSolarized.nvim/assets/369238/d1a40ba2-e0cf-4757-b84e-88ed26300455)

Maybe the following?

```lua
M.light = {
  -- ...
  diff_add = '#caffca',
  diff_change = '#ffffca',
  diff_delete = '#ffcaca',
  diff_text = '#e8e8b3',
  -- ...
}
```

![Screenshot from 2024-02-22 19-00-47](https://github.com/Tsuzat/NeoSolarized.nvim/assets/369238/32c78d14-715e-470b-b619-b0b895089f7f)

# CursorLine and CursorColumn

I sometimes use these options to make "crosshairs" for my cursor (especially when drawing boxes in `:h 'virtualedit'` mode). [theme.lua](https://github.com/Tsuzat/NeoSolarized.nvim/blob/3089cb703e947e6433a2c2c1191b97e63804b300/lua/NeoSolarized/theme.lua#L20) currently sets the color to `NONE`, but I would suggest linking it to `CursorLine`:

```lua
theme.highlights = {
  -- ...
  CursorLine = { link = 'CursorColumn' }
  -- ...
}
```

![Screenshot from 2024-02-22 19-13-15](https://github.com/Tsuzat/NeoSolarized.nvim/assets/369238/c9c71963-8a3d-4aa9-b07a-3d6aa940891f)

# ColorColumn

The default `c.blue` background for `:h 'colorcolumn'` "rulers" might be a bit too vibrant:

![Screenshot from 2024-02-22 19-16-12](https://github.com/Tsuzat/NeoSolarized.nvim/assets/369238/3ef0407e-5220-4773-88a0-fda47815fa7e)

Maybe use `c.bg1` by default instead?

![Screenshot from 2024-02-22 19-16-25](https://github.com/Tsuzat/NeoSolarized.nvim/assets/369238/4431a274-f03e-45b8-8221-2941bb8430a2)

**Comment by Tsuzat** [comment]
@komputerwiz , Thanks for an amazing suggestions. I would appreciate a pull request. Happy Coding :)

**Comment by komputerwiz** [comment]
Pull request submitted! 👍 

Please Let me know if you have any thoughts or comments or if you want to let others have a chance to weigh in.
Otherwise, feel free to merge and close the issue.

Thanks again for the great work!
