### ISSUE TITLE
How do I change the background color of a highlighted variable?

### ISSUE THREAD

**Issue by joobus** [Tsuzat/NeoSolarized.nvim#21]
In the screenshot below, what is the name of the highlight group which is making "lunarvim/colorschemes" appear with a yellow background?  I would like to change the color.

![neosolarized-highlight](https://github.com/Tsuzat/NeoSolarized.nvim/assets/24600223/6c05cbdb-4414-450e-a0f3-64ae95d59027)

**Comment by joobus** [comment]
Figured it out: `CurrentWord`.  Add this to your config to change the color:

```lua
  -- Add specific highlight groups
  on_highlights = function(highlights, colors)
    highlights.CurrentWord.bg = colors.blue
  end,
```

**Comment by Tsuzat** [comment]
Amazing. Happy Coding.
