### ISSUE TITLE
Background colors in diff mode make changes unreadable 

### ISSUE THREAD

**Issue by mohelm** [Tsuzat/NeoSolarized.nvim#3]
Hey - first, many thanks for this fantastic color scheme.

I only have one slight issue - at least in my configuration - when I diff to files the background colors make the text unreadable. Is it possible to fix this?

Thanks!!

![Bildschirmfoto 2022-10-28 um 15 57 57](https://user-images.githubusercontent.com/17968693/198628108-5b48c84e-2aea-4a42-99a2-06e41e51c925.png)

**Comment by Tsuzat** [comment]
Hey, thanks for reporting the issue. I have added new colors for `diff` mode. 
It may not look good so feel free to make changes. Pull requests are welcomed.

![fix#3](https://user-images.githubusercontent.com/70003855/198877210-5b28f18f-6db2-4878-98b3-783eccbc5f73.png)

**Comment by mohelm** [comment]
Thank you!
