### ISSUE TITLE
Add ability to override highlight groups?

### ISSUE THREAD

**Issue by vinsonchuong** [Tsuzat/NeoSolarized.nvim#5]
Thanks a lot for writing this plugin! I've been stuck using [altercation/vim-colors-solarized](https://github.com/altercation/vim-colors-solarized) for a long time. Finally, there's a well-maintained one I can switch to!

I was wondering if you could include a clean way to override parts of the theme in Lua. I noticed that [folke/tokyonight.nvim](https://github.com/folke/tokyonight.nvim) takes in `on_colors` and `on_highlights` functions for doing that.

Currently, I'm accomplishing this by doing:

```lua
local colors = require("NeoSolarized.colors").setup()
vim.api.nvim_command("highlight Normal guifg=" .. colors.fg2)
```

But, I'm thinking that the following would feel a bit cleaner.

```lua
require("NeoSolarized").setup({
  on_highlights = function(highlights, colors)
    highlights.Normal.fg = colors.fg2
  end
})
```

Let me know what you think! I could submit a pull request as well if that helps.

**Comment by Tsuzat** [comment]
Hey @vinsonchuong, I'm glad that you like the color scheme. I like the idea and I'll definitely try to work on that. but I cannot promise any updates very soon. I'm too busy with my academics.
Moreover, If you feel like the changes are necessary, you can submit a pull request. But again, I can not promise that I'll review and merge it very soon.
Happy Coding. ❤️

**Comment by Tsuzat** [comment]
I have added the feature and thanks for the recommendation. Feel free to reopen the issue if you feel so. Happy coding❤
