### ISSUE TITLE
GUI colors not showing

### ISSUE THREAD

**Issue by vintingb** [Tsuzat/NeoSolarized.nvim#6]
I really like this pure lua theme. It's fine in terminal but when I try to use neovim gui neovide,colors not showing.
I read this FAQ:

https://neovide.dev/faq.html#the-terminal-displays-fallback-colorsterminal-does-not-show-my-colors

**Comment by Tsuzat** [comment]
@vintingb I do not use GUI clients like Neovide, so I actually did not know about this issue. So, unfortunately, you have to figure out it by yourself. If you do so, you can submit a pull request.
Thanks for using the project and Happy Coding ❤
