### ISSUE TITLE
Doesn't work well with lightspeed.nvim

### ISSUE THREAD

**Issue by towry** [Tsuzat/NeoSolarized.nvim#7]
![截屏2022-12-15 10 07 59](https://user-images.githubusercontent.com/8279858/207755728-bdadbda1-1a31-4d11-ab3e-afbcb9633678.png)

It's hard to find the highlighted character in the above section. In `gruvbox` theme, the background is dark and highlighted character is white which is very distinct. 

BTW, this is the most good solarized theme for nvim I have found so far, great work.

**Comment by Tsuzat** [comment]
Hey, I can understand the pain. I have improved the highlight groups based on **gruvbox-material**.
If you feel like changing the highlight groups based on your liking, you can do it in the setup config. 

You can change any highlight group based on your liking, e.g.
```lua
-- Add specific highlight groups
  on_highlights = function(highlights, colors) 
    highlights.Include.fg = colors.red -- Using `red` foreground for Includes
  end,
```

You can refer to `README.md` for more details.
Thanks for using the project and Happy Coding ❤
