### ISSUE TITLE
Coloring of quickfix list

### ISSUE THREAD

**Issue by mohelm** [Tsuzat/NeoSolarized.nvim#9]
Hi Tsuzat, thanks again for the amazing theme!

I have a bit of an issue that the quickfix list is not that readable:

[
![Bildschirm­foto 2023-02-15 um 06 05 47](https://user-images.githubusercontent.com/17968693/218937584-1d256da5-6ca9-41e2-bbd7-79a3ba0b9936.png)
](url)

Is there a chance you could look into this, or is this an issue on my side?

Thanks!

**Comment by Tsuzat** [comment]
Hey @mohelm , You can change the highlight group for `QuickFixLine` from the configuration of `NeoSolarized`. Please check out the [documentation](https://github.com/Tsuzat/NeoSolarized.nvim#%EF%B8%8F-configuration). You can add the following lines to your setup, 
```lua
-- Add specific hightlight groups
on_highlights = function(highlights, colors) 
  highlights.QuickFixLine.bg = colors.none -- Removing background from QuickFixLine
end, 
```
You can find the `QuickFixLine` highlight group [here](https://github.com/Tsuzat/NeoSolarized.nvim/blob/d28e79c3be31a8e2554278d40780a268184bb365/lua/NeoSolarized/theme.lua#L55) in the code. Let me know if this solves the issue.

Feel free to play with `hightlight` groups and submit a PR if required. Happy Coding ❤️

**Comment by mohelm** [comment]
thanks a bunch. set it to none for now. might play around with the highlights group later. thx.
